#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
TARGET_ROOT="${ROOT_DIR}/ghostlink"

log() {
  printf '==> %s\n' "$1"
}

ensure_parent_dir() {
  local path="$1"
  mkdir -p "$(dirname "${path}")"
}

emit_from_template() {
  local target="$1"
  local template="$2"
  local dest

  if [[ "${target}" == /* ]]; then
    dest="${ROOT_DIR}${target}"
  else
    dest="${TARGET_ROOT}/${target}"
  fi

  if [[ "${target}" == *'*'* ]]; then
    local dir_path
    dir_path="${dest%/*}"
    if [[ "${dir_path}" == "${dest}" ]]; then
      dir_path="${dest}"
    fi
    mkdir -p "${dir_path}"
    local placeholder_file="${dir_path}/PLACEHOLDER_from_template_${template}.md"
    log "materializing placeholder ${placeholder_file}"
    cat >"${placeholder_file}" <<EOF
# GhostLink template placeholder

This file was generated by \`kernel/REBUILD_MAX.sh\` to satisfy the rebuild
step \`emit ${target} from template:${template}\` defined in
\`kernel/gl-kernel.max.json\`.

Replace this placeholder with the output of the \`${template}\` template when
available.
EOF
  else
    ensure_parent_dir "${dest}"
    log "writing template stub ${dest}"
    cat >"${dest}" <<EOF
"""Autogenerated stub for ${target} (template: ${template}).

Generated by kernel/REBUILD_MAX.sh using the rebuild metadata declared in
kernel/gl-kernel.max.json. Replace this stub with the rendered template output
for '${template}'.
"""

if __name__ == "__main__":
    raise SystemExit("Replace template stub for ${target}")
EOF
  fi
}

write_seed_file() {
  local target="$1"
  local dest

  if [[ "${target}" == /* ]]; then
    dest="${ROOT_DIR}${target}"
  else
    dest="${TARGET_ROOT}/${target}"
  fi

  ensure_parent_dir "${dest}"
  log "writing seed placeholder ${dest}"
  cat >"${dest}" <<'EOF'
# Ghostcore seed placeholder

This file was generated automatically by `kernel/REBUILD_MAX.sh`. Supply the
true Ghostcore seed content here when the build templates are available.
EOF
}

write_placeholder_group() {
  local entries="$1"
  local IFS=','
  read -ra parts <<<"${entries}"

  for raw_part in "${parts[@]}"; do
    local part
    part="${raw_part# }"
    part="${part##write }"
    if [[ -z "${part}" ]]; then
      continue
    fi
    emit_from_template "${part}" "manual"
  done
}

create_placeholder_tests() {
  local target="$1"
  local dest="${TARGET_ROOT}/${target%/*}"
  mkdir -p "${dest}"
  local file="${dest}/test_placeholder.py"
  log "creating test scaffold ${file}"
  cat >"${file}" <<'EOF'
"""Placeholder test suite for the GhostLink kernel rebuild.

Replace these tests with the real suite generated from templates or source
material.
"""


def test_placeholder():
    assert True, "Replace placeholder test once real tests are generated"
EOF
}

process_step() {
  local step="$1"

  case "${step}" in
    "")
      return
      ;;
    ("mkdir -p "*)
      log "executing: ${step}"
      bash -euc "${step}"
      ;;
    ("emit "*)
      local payload template
      payload="${step#emit }"
      template="${payload##* from template:}"
      payload="${payload%% from template:*}"
      emit_from_template "${payload}" "${template}"
      ;;
    ("write "*" from seed")
      local payload
      payload="${step#write }"
      payload="${payload% from seed}"
      write_seed_file "${payload}"
      ;;
    ("write "*)
      local payload
      payload="${step#write }"
      write_placeholder_group "${payload}"
      ;;
    ("create "*)
      local payload
      payload="${step#create }"
      create_placeholder_tests "${payload}"
      ;;
    (*)
      log "warning: unhandled rebuild step '${step}'"
      ;;
  esac
}

while IFS= read -r step; do
  process_step "${step}"
done < <(jq -r '.rebuild.steps[]' "${SCRIPT_DIR}/gl-kernel.max.json")

log "rebuild scaffold complete"
