"""Autogenerated stub for runtime/ghostlink.py (template: cli).

Generated by kernel/REBUILD_MAX.sh using the rebuild metadata declared in
kernel/gl-kernel.max.json. Replace this stub with the rendered template output
for 'cli'.
"""

if __name__ == "__main__":
    raise SystemExit("Replace template stub for runtime/ghostlink.py")
